mylist/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mylist'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new_list$', views.add_new_list, name='new_list'),
    url(r'^rename=(?:(?P<list_id>[0-9]+))?$', views.rename_list, name='rename_list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.MovieListEditView.as_view(), name='list-edit'),
    url(r'^add=(?P<movie_id>[0-9]+)', views.add_movie_to_list, name='add_to_list'),
    url(r'^(?P<pk>[0-9]+)/list/$', views.MovieListView.as_view(), name='list-detail'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.MovieDetailView.as_view(), name='movie-detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.MovieUpdateView.as_view(), name='movie-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.MovieDeleteView.as_view(), name='movie-delete'),
    url(r'^list=(?P<list_id>[0-9]+)&set_watched=(?P<movie_id>[0-9]+)', views.set_movie_watched, name='set_watched'),
    url(r'^list=(?P<list_id>[0-9]+)&clear_watched=(?P<movie_id>[0-9]+)', views.clear_movie_watched, name='clear_watched'),


]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    url(r'^$', views.TopThisMonth.as_view(), name='index'),
    url(r'^browse=', views.SearchView.as_view(), name='browse'),
    url(r'^movies$', views.BrowseMovies.as_view(), name='movies'),
    url(r'^genre=(?P<genre_id>[0-9]+)$', views.GenreView.as_view(), name='by_genre'),
    url(r'^year=(?P<year>[0-9]+)$', views.YearView.as_view(), name='by_year'),
    url(r'^top-this-month', views.TopThisMonth.as_view(), name='top-this-month'),
    url(r'^top-this-year', views.TopThisYear.as_view(), name='top-this-year'),
    url(r'^(?P<movie_id>[0-9]+)$', views.MovieDetail.as_view(), name='movie-detail'),
]

users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-ai'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-pi'),
    url(r'^settings/fl=(?P<pk>[0-9]+)$', views.user_settings_fl, name='user-settings-fl'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&search=$', views.search_users, name='search-users'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&add=(?P<add_pk>[0-9]+)$', views.add_friend, name='add-friend'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&remove=(?P<remove_pk>[0-9]+)$', views.remove_friend, name='remove-friend'),
]

mylist/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from users.models import UserProfile
import tmdbsimple as tmdb
import os
import yaml

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),"configs.yml"), 'r') as ymlfile:
    cfg = yaml.load(ymlfile)
    tmdb.API_KEY = cfg['tmdb']['api_key']


class Movie(models.Model):
    tmdb_id = models.IntegerField(blank=False, null=True)
    title = models.CharField(max_length=120,unique=True)
    release_date = models.CharField(max_length=32, null=True, blank=True)
    overview = models.TextField()
    runtime = models.CharField(max_length=12, blank=True, null=True)
    backdrop_url = models.CharField(max_length=512, null=True, blank=True)
    poster_url = models.CharField(max_length=512,null=True, blank=True)
    last_edited = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('mylist:index')

    def get_image(self):
        conf = tmdb.Configuration()
        base_url = conf.info()['images']['base_url']
        size = conf.info()['images']['poster_sizes'][2]
        m = tmdb.Movies(self.id)
        url_parts = [base_url,size,m.info()['poster_path']]

        return ''.join(url_parts)

    def __str__(self):
        return self.title

'''
class Genre(models.Model):
    genre_id = models.IntegerField(null=True, blank=False)
    name = models.CharField(max_length=64)
    movie = models.ManyToManyField(Movie)
'''


class MovieList(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=120, unique=True)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    shared = models.BooleanField(default=False)
    shared_with = models.ManyToManyField(UserProfile, blank=True, related_name='shared_with')
    movies = models.ManyToManyField(Movie, through='MovieListMembership', through_fields=('movie_list','movie'))

    def get_absolute_url(self):
        return reverse('mylist:index')

    def __str__(self):
        return self.list_name


class MovieListMembershipManager(models.Manager):
    def movies_for_list(self, list):
        return self.get_queryset().filter(movie_list=list)


class MovieListMembership(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    movie_list = models.ForeignKey(MovieList, on_delete=models.CASCADE)
    rating = models.CharField(max_length=12, null=True, blank=True)
    favorite = models.BooleanField(default=False)
    watched = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_watched = models.DateTimeField(null=True, blank=True)
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='movie_list_owner')

    objects = MovieListMembershipManager()

    def get_movie_title(self):
        return self.movie

    def get_movie_overview(self):
        return self.movie.overview

    def get_list_name(self):
        return self.move_list

    def __str__(self):
        return self.owner.user.username

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms
from mylist.models import MovieList


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'type': 'text','class':'input',
                                                           'placeholder': 'The Martian'}),
                             label='Search', max_length=120)


class AddMovieForm(forms.Form):
    movie_lists = forms.ModelChoiceField(queryset=MovieList.objects.all(),empty_label='Select a list')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(AddMovieForm, self).__init__(*args, **kwargs)

        if user is not None:
            self.fields['movie_lists'].queryset = MovieList.objects.filter(owner=user)
        else:
            self.fields['movie_lists'] = ['Not Logged In']

search/views.py
from django.shortcuts import get_object_or_404, render
from .forms import SearchForm, AddMovieForm
from django.views.generic.base import TemplateView
from django.utils import timezone
from mylist.models import MovieListMembership
import tmdbsimple as tmdb
import yaml
import os


''' 
CONSTANTS:
- MAX_RESULTS: Sets the number of search results to return 
- CUR_YEAR: Sets the current year
- CONFIG: Config file to load
'''
MAX_RESULTS = 12
CUR_YEAR = timezone.now().year
CONFIG = 'configs.yml'

# Load TMDB API Key

''' Loads the config file that contains the API key for TheMovieDatabase.org '''
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),CONFIG), 'r') as ymlfile:
    cfg = yaml.load(ymlfile)
    tmdb.API_KEY = cfg['tmdb']['api_key']


# Retrieve poster url base from TMDB API
def get_poster_base():
    conf = tmdb.Configuration()
    secure_base_url = conf.info()['images']['secure_base_url']
    size = conf.info()['images']['poster_sizes'][2]
    url = [secure_base_url, size]
    return ''.join(url)


# Retrieve backdrop url from TMDB API
def get_backdrop_base():
    conf = tmdb.Configuration()
    secure_base_url = conf.info()['images']['secure_base_url']
    size = conf.info()['images']['backdrop_sizes'][2]
    url = [secure_base_url, size]
    return ''.join(url)


# Builds the list of years from 1900 to current year
def get_years(seed_year=1900):
    year_range = []
    for year in range(CUR_YEAR, seed_year, -1):
        year_range.append(year)
    return year_range


# Return a list of movie genres from TMDB API
def get_movie_genres():
    return tmdb.Genres().list()['genres']


# Main view for the Browse portion of the app
class IndexView(TemplateView):
    template_name = 'search/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            watched_movies = MovieListMembership.objects.filter(owner=self.request.user.userprofile, watched=True)
        else:
            watched_movies = None
        form = SearchForm()
        context['form'] = form
        context['poster'] = get_poster_base()
        context['year_list'] = get_years()
        context['genre_list'] = get_movie_genres()

        return context


class BrowseMovies(IndexView):

    def get_context_data(self, **kwargs):
        context = super(BrowseMovies, self).get_context_data(**kwargs)
        d = tmdb.Discover()
        response = d.movie(sort_by='popularity.desc')
        context['browse_header'] = 'All Movies'
        context['response'] = response['results'][:MAX_RESULTS]
        return context


class SearchView(IndexView):

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if request.method == 'GET':
            form = SearchForm(request.GET)
            if form.is_valid():
                q = tmdb.Search()
                response = q.movie(query=form.cleaned_data['search'])
                context['browse_header'] = 'Search Results'
                context['response'] = response['results'][:MAX_RESULTS]
                return render(request, 'search/index.html', context)
        else:
            form = SearchForm()

        return render(request, 'search/index.html', context)


class TopThisMonth(IndexView):

    def get_context_data(self, **kwargs):
        context = super(TopThisMonth, self).get_context_data(**kwargs)
        d = tmdb.Discover()
        t = timezone.now()
        last_month = t.replace(day=1) - timezone.timedelta(days=1)
        date = timezone.datetime(
            year=timezone.now().year,
            month=last_month.month,
            day=1
        )
        response = d.movie(primary_release_date_gte=date.date())
        context['browse_header'] = 'Top Movies since '
        context['date'] = date.date()
        context['response'] = response['results'][:MAX_RESULTS]

        return context


class TopThisYear(IndexView):

    def get_context_data(self, **kwargs):
        context = super(TopThisYear, self).get_context_data(**kwargs)
        d = tmdb.Discover()
        date = timezone.datetime(
            year=timezone.now().year,
            month=1,
            day=1
        )
        response = d.movie(primary_release_date_gte=date.date())
        context['browse_header'] = 'Top Movies since '
        context['date'] = date.date()
        context['response'] = response['results'][:MAX_RESULTS]

        return context


class GenreView(IndexView):

    def get_context_data(self, **kwargs):
        context = super(GenreView, self).get_context_data(**kwargs)
        d = tmdb.Discover()
        response = d.movie(with_genres=kwargs['genre_id'])
        genre_list = get_movie_genres()

        for item in genre_list:
            if str(item['id']) == kwargs['genre_id']:
                context['browse_header'] = item['name']

        context['response'] = response['results'][:MAX_RESULTS]

        return context


class YearView(IndexView):

    def get_context_data(self, **kwargs):
        context = super(YearView, self).get_context_data(**kwargs)
        d = tmdb.Discover()
        response = d.movie(year=kwargs['year'])
        context['browse_header'] = kwargs['year']
        context['response'] = response['results'][:MAX_RESULTS]
        return context


class MovieDetail(IndexView):

    template_name = 'search/movie-detail.html'

    def get_context_data(self, **kwargs):
        q = tmdb.Movies(kwargs['movie_id'])
        response = q.info()
        if self.request.user.is_authenticated:
            form = AddMovieForm(user=self.request.user.userprofile)
        else:
            form = AddMovieForm()

        context = {'movie': response, 'poster': get_poster_base(), 'backdrop': get_backdrop_base(), 'add_movie_form': form}
        return context

search/templates/search/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">
        <title>{% block page_title %}{% endblock %}</title>
        <!-- {% load static %} -->
        <!-- Bootstrap core CSS -->
        <link href="{% static '/css/bulma.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <!--<link href="{% static 'mylist/css/ie10-viewport-bug-workaround.css' %}"
            rel="stylesheet">-->
            <!-- Custom styles for this template -->
            <link href="{% static '/css/dropdown.css' %}" rel="stylesheet">
            <link href="{% static '/css/base-main.css' %}" rel="stylesheet">
            {% block per_page_style %}
            {% endblock %}
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
            <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
        </head>
        <body>
            <header>
                {% include 'navbar.html' %}
            </header>
            
            <section class="hero">
                {% block browse_hero %}
                    {% include 'search/browse-hero.html' %}
                {% endblock browse_hero %}
            </section>
            
            <section class="section">
                <div class="container">
                    {% block main_content_header %}
                    {% endblock %}
                    {% block main_content %}
                    {% endblock %}
                </div>
            </section>

            <footer class="footer">
            {% include 'footer.html' %}
            </footer>
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script type="text/javascript" src="{% static '/js/jq-modal.js' %}"></script>
            <script type="text/javascript" src="{% static '/js/dropdown.js' %}"></script>
            <!--<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>-->
        </body>
    </html>

search/templates/search/browse-hero.html
<div class="container browse">
    <div class="container form">
        <form action="{% url 'search:browse' %}" method="get" accept-charset="utf-8" role="search">
            <div class="field has-addons">
                <p class="control is-expanded">
                    {{ form.search }}
                </p>
                <p class="control">
                    <a class="button is-primary">
                        Search
                    </a>
                </p>
            </div>
        </form>
    </div>
</div>
<nav class="navbar browse-nav">
    <div class="container">
        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item">Popular <br /><small><span class="tag is-warning">Work in progress</span></small></a>
                <a class="navbar-item">Classics <br /><small><span class="tag is-warning">Work in progress</span></small></a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Genre</a>
                    <div class="navbar-dropdown">
                        {% for genre in genre_list %}
                            <a class="navbar-item" href="{% url 'search:by_genre' genre.id %}"> {{ genre.name }} </a><
                        {% endfor %}
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Year</a>
                    <div class="navbar-dropdown">
                        {% for year in year_list %}
                            <li><a class="navbar-item" href="{% url 'search:by_year' year %}"> {{ year }} </a></li>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

search/templates/search/index.html
{% extends 'base.html' %}
{% block page_title %} Our List | {% if user.is_authenticated %} {{ user }} {% else %} Guest {% endif %}{% endblock %}
{% load static %}
{% block per_page_style %}
    <link href="{% static '/search/browse.css' %}" rel="stylesheet">
{% endblock %}
<!-- Bootstrap core CSS -->
{% block main_content_header %}
    <div class="level">
        <div class="level-left">
            <h1 class="title">Browsing | <strong> {{ browse_header }} {{ date|date}} </strong></h1>
        </div>
    </div>
{% endblock %}
{% block main_content %}
    <div class="tile is-ancestor">
        <div class="tile is-parent movie-tiles">
            {% for movie in response %}
                <div class="tile is-3 is-child movie-box">
                    <div class="card material-shadow-d2">
                        <span class="tag is-rating">{{ movie.vote_average }}
                            <span class="icon is-small">
                                <i class="fa fa-star" aria-hidden="true"></i>
                            </span>
                        </span>
                        <div class="card-image">
                            <figure class="image is-16by9">
                                <img src="{{ poster }}{{ movie.backdrop_path }}" alt="Image">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    <p class="title is-5">{{ movie.title|truncatechars:28 }}</p>
                                    <p class="subtitle is-6">{{ movie.release_date }}</p>
                                </div>
                            </div>
                            <footer class="card-footer">
                                <div class="field is-grouped">
                                    <a href="{% url 'search:movie-detail' movie.id %}" class="button">Details</a>
                                    <a class="button">
                                        <span class="icon is-small">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </span>
                                    </a>
                                </div>
                            </footer>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block per_page_jquery %}
    <script>
    $(document).ready(function(){
    $( ".hero" ).addClass( "browse" );
    });
    </script>
{% endblock per_page_jquery %}

search/templates/search/movie-detail.html
{% extends 'base.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
{% block per_page_style %}
    <link href="{% static 'search/browse.css' %}" rel="stylesheet">
	<style type="text/css" media="screen">
		
	.box {
	min-height: 350px;
	border-radius: 0px;
	display: flex;
	align-items: center;
	justify-content: left;
	position: relative;
	}
	.box:before {
	content: ' ';
	display: block;
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	z-index: 1;
	opacity: 0.6;
	background-image: url("{{ backdrop }}{{ movie.backdrop_path }}");
	background-repeat: no-repeat;
	background-position: 50% 0;
	-ms-background-size: cover;
	-o-background-size: cover;
	-moz-background-size: cover;
	-webkit-background-size: cover;
	background-size: cover;
	}
	.box.movie-detail .title {
		color: #fff;
	}
	.box.movie-detail .subtitle {
		color: #f5f5f6;
	}
	.grad {
	min-height: 350px;
	border-radius: 0px;
	align-items: center;
	justify-content: left;
	position: relative;
	}
	.grad:before {
	content: ' ';
	display: block;
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	z-index: 2;
	background: black; /* For browsers that do not support gradients */
	background: -webkit-linear-gradient(left top, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Safari 5.1 to 6.0 */
	background: -o-linear-gradient(bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Opera 11.1 to 12.0 */
	background: -moz-linear-gradient(bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Firefox 3.6 to 15 */
	background: linear-gradient(to bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* Standard syntax */
	}
	.media {
	padding:50px;
	z-index: 3;
	}
	.media-content .main-cast {
		margin-top: -1rem;
		margin-bottom: 0.5rem;
	}
	.media-content .block.title {
		margin-bottom: 0rem
	}
	.media-content .block.overview p {
		color: #fff;
	}
	.media-content .block.rating {
		color: #fff;
	}
	</style>
{% endblock %}


{% block browse_hero %}
	<div class="toolbar">
		<nav class="level">
			<!-- Left side -->
			<div class="level-left">
			</div>
			<!-- Right side -->
			<div class="level-right">
				{% if user.is_authenticated %}
					<form action="{% url 'mylist:add_to_list' movie.id %}" method="post" accept-charset="utf-8">
						{% csrf_token %}
						<div class="field is-horizontal">
						<div class="field-body">
						<div class="field has-addons">
							<p class="control">
								<span class="select">{{ add_movie_form.movie_lists }}</span>
							</p>
							<p class="control">
								    <button class="button is-primary" type="submit" >
								    <span class="icon is-small">
								    <i class="fa fa-plus" aria-hidden="true"></i>
								    </span>
								    </button>
							</p>
						</div>
						<div class="field">
							<p class="control">
								    <button class="button is-primary" type="submit" >
								    <span class="icon is-small">
								    <i class="fa fa-eye" aria-hidden="true"></i>
								    </span>
								    </button>
							</p>
							</div>
							</div>
						</div>
					</form>
				{% endif %}
			</div>
		</nav>
	</div>
	<!-- Main container -->
		<div class="grad">
			<div class="box movie-detail">
				
				<article class="media">
					<div class="media-left">
						<figure class="image">
							<img src="{{ poster }}{{ movie.poster_path }}" alt="Image">
						</figure>
					</div>
					<div class="media-content">
						<div class="block title">
							<h3 class="title is-3"> {{ movie.title }} </h3>
							<h5 class="subtitle is-5"> {{ movie.release_date }} </h5>
						</div>
						<p class="block rating"> Movie Rating </p>
						<div class="block is-48x48 main-cast">
							<img src="http://bulma.io/images/placeholders/48x48.png">
							<img src="http://bulma.io/images/placeholders/48x48.png">
						</div>
						<div class="block overview">
							<p>{{ movie.overview }}</p>
						</div>
					</div>
				</article>
			</div>
		</div>
{% endblock browse_hero %}
{% block main_content %}
{% endblock main_content %}

search/templates/search/search_filter.html
<aside class="menu">
    <p class="menu-label"> Top 10 Movies </p>
    <ul class="menu-list">
        <li><a href="{% url 'search:top-this-month' %}"> This Month </a></li>
        <li><a href="{% url 'search:top-this-year' %}"> This Year </a></li>
    </ul>
    <p class="menu-label"> Browse By Genre </p>
    <ul class="menu-list">
        <li><a href=""> Sci-Fi </a></li>
        <li><a href=""> Drama </a></li>
        <li><a href=""> Comedy </a></li>
        <li><a href=""> Action </a></li>
    </ul>

</aside>