mylist/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mylist'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new_list$', views.add_new_list, name='new_list'),
    url(r'^rename=(?:(?P<list_id>[0-9]+))?$', views.rename_list, name='rename_list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.MovieListEditView.as_view(), name='list-edit'),
    url(r'^add=(?P<movie_id>[0-9]+)', views.add_movie_to_list, name='add_to_list'),
    url(r'^(?P<pk>[0-9]+)/list/$', views.MovieListView.as_view(), name='list-detail'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.MovieDetailView.as_view(), name='movie-detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.MovieUpdateView.as_view(), name='movie-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.MovieDeleteView.as_view(), name='movie-delete'),
    url(r'^list=(?P<list_id>[0-9]+)&set_watched=(?P<movie_id>[0-9]+)', views.set_movie_watched, name='set_watched'),
    url(r'^list=(?P<list_id>[0-9]+)&clear_watched=(?P<movie_id>[0-9]+)', views.clear_movie_watched, name='clear_watched'),


]

users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-ai'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-pi'),
    url(r'^settings/fl=(?P<pk>[0-9]+)$', views.user_settings_fl, name='user-settings-fl'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&search=$', views.search_users, name='search-users'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&add=(?P<add_pk>[0-9]+)$', views.add_friend, name='add-friend'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&remove=(?P<remove_pk>[0-9]+)$', views.remove_friend, name='remove-friend'),
]

mylist/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from users.models import UserProfile
import tmdbsimple as tmdb
import os
import yaml

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),"configs.yml"), 'r') as ymlfile:
    cfg = yaml.load(ymlfile)
    tmdb.API_KEY = cfg['tmdb']['api_key']


class Movie(models.Model):
    tmdb_id = models.IntegerField(blank=False, null=True)
    title = models.CharField(max_length=120,unique=True)
    release_date = models.CharField(max_length=32, null=True, blank=True)
    overview = models.TextField()
    runtime = models.CharField(max_length=12, blank=True, null=True)
    backdrop_url = models.CharField(max_length=512, null=True, blank=True)
    poster_url = models.CharField(max_length=512,null=True, blank=True)
    last_edited = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('mylist:index')

    def get_image(self):
        conf = tmdb.Configuration()
        base_url = conf.info()['images']['base_url']
        size = conf.info()['images']['poster_sizes'][2]
        m = tmdb.Movies(self.id)
        url_parts = [base_url,size,m.info()['poster_path']]

        return ''.join(url_parts)

    def __str__(self):
        return self.title

'''
class Genre(models.Model):
    genre_id = models.IntegerField(null=True, blank=False)
    name = models.CharField(max_length=64)
    movie = models.ManyToManyField(Movie)
'''


class MovieList(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=120, unique=True)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    shared = models.BooleanField(default=False)
    shared_with = models.ManyToManyField(UserProfile, blank=True, related_name='shared_with')
    movies = models.ManyToManyField(Movie, through='MovieListMembership', through_fields=('movie_list','movie'))

    def get_absolute_url(self):
        return reverse('mylist:index')

    def __str__(self):
        return self.list_name


class MovieListMembershipManager(models.Manager):
    def movies_for_list(self, list):
        return self.get_queryset().filter(movie_list=list)


class MovieListMembership(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    movie_list = models.ForeignKey(MovieList, on_delete=models.CASCADE)
    rating = models.CharField(max_length=12, null=True, blank=True)
    favorite = models.BooleanField(default=False)
    watched = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_watched = models.DateTimeField(null=True, blank=True)
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='movie_list_owner')

    objects = MovieListMembershipManager()

    def get_movie_title(self):
        return self.movie

    def get_movie_overview(self):
        return self.movie.overview

    def get_list_name(self):
        return self.move_list

    def __str__(self):
        return self.owner.user.username

mylist/forms.py
from django import forms
from django.forms import ModelForm, TextInput, CheckboxInput
from mylist.models import MovieList
from users.models import UserProfile


class RenameListForm(forms.Form):
    list_name = forms.CharField(widget=TextInput(attrs={'type': 'text','class':'input',
                                                        'placeholder': 'List Name'}),
                                label='List Name', max_length=120)


class EditListForm(ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(EditListForm, self).__init__(*args, **kwargs)
        self.fields['shared_with'].queryset = UserProfile.objects.exclude(user=user)

    class Meta:
        model = MovieList
        fields = ['list_name', 'shared', 'shared_with']
        widgets = {
            'list_name': TextInput(attrs={'type': 'text','class':'input',
                                          'placeholder': 'List Name'}),
            'shared': CheckboxInput(attrs={'type': 'checkbox'}),
        }

mylist/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import DeleteView, UpdateView
from .models import Movie, MovieList, MovieListMembership
from search.forms import SearchForm, AddMovieForm
from .forms import EditListForm, RenameListForm
import tmdbsimple as tmdb


'''
Simple percentage function for movie stats
'''


def get_percent(watched, total):
    if total > 0:
        return watched / total * 100
    else:
        return 0

'''
Main view, all other views in My Lists should inherit
from this one.
'''


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'mylist/index.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IndexView, self).get_context_data(**kwargs)
        owner = self.request.user.userprofile
        lists = MovieList.objects.filter(owner=owner)
        shared_with_me = MovieList.objects.filter(shared_with=owner)

        # Define Context
        extra_context = {
            'movie_count': MovieListMembership.objects.filter(owner=owner).count(),
            'my_lists': lists,
            'lists_shared_with_me': shared_with_me,
            'form': SearchForm(),
            'rename_form': RenameListForm(),
            'sidebar': 'mylist/sidebar_nav.html'
        }

        context.update(extra_context)

        return context


'''

Movie List Views

'''


class MovieListView(IndexView):
    model = MovieList
    template_name = 'mylist/movielist-detail.html'

    def get_context_data(self, **kwargs):
        context = super(MovieListView, self).get_context_data(**kwargs)
        list_id = self.kwargs['pk']
        owner = self.request.user.userprofile
        movies_in_list = MovieListMembership.objects.movies_for_list(list_id)
        list_watched_count = movies_in_list.filter(watched=True).count()
        all_movies = MovieListMembership.objects.filter(owner=owner)
        all_watched_count = all_movies.filter(watched=True).count()

        extra_context = {
            'movie_list': MovieListMembership.objects.movies_for_list(list_id),
            'list_id': list_id,
            'list': MovieList.objects.get(id=list_id),
            'movies_watched': list_watched_count,
            'watched_percent': get_percent(list_watched_count, movies_in_list.count()),
            'all_movies_watched': all_watched_count,
            'all_movies_watched_percent': get_percent(all_watched_count, all_movies.count()),
            'movies': movies_in_list,
            'rename_form': RenameListForm()
        }

        context.update(extra_context)

        return context


def rename_list(request, list_id, **kwargs):
    if request.method == 'POST':
        form = RenameListForm(request.POST)
        if form.is_valid():
            movie_list = get_object_or_404(MovieList, pk=list_id)
            movie_list.list_name = form.cleaned_data['list_name']
            movie_list.save()
        return HttpResponseRedirect(reverse('mylist:index', ))
    else:
        return render(request, 'mylist/index.html')


class MovieListEditView(UpdateView):
    model = MovieList
    form_class = EditListForm

    def get_context_data(self, **kwargs):
        owner = self.request.user.userprofile
        context = super(MovieListEditView, self).get_context_data(**kwargs)
        lists = MovieList.objects.filter(owner=owner)
        list_name = lists.filter(id=self.kwargs['pk'])

        extra_context = {
            'my_lists': lists,
            'list_id': self.kwargs['pk'],
            'list_name': self.get_form_kwargs()['instance'],
            'sidebar': 'mylist/sidebar_nav.html'
        }

        context.update(extra_context)

        return context

    def get_form_kwargs(self):
        kwargs = super(MovieListEditView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

'''

Movie Detail Views

'''

class MovieDetailView(DetailView):
    model = Movie
    template_name = 'mylist/movie-detail.html'
    context_object_name = 'movie'


class MovieUpdateView(UpdateView):
    model = Movie
    fields = ['title', 'year', 'overview']
    template_name_suffix = '-update-form'


class MovieDeleteView(DeleteView):
    model = Movie
    context_object_name = 'item'
    success_url = reverse_lazy('mylist:index')


def add_new_list(request):
    if request.method == 'GET':
        new_list = MovieList.objects.create(owner=request.user.userprofile,
                                            list_name="New List " + str(timezone.now().microsecond))
        new_list.save()

    return HttpResponseRedirect(reverse('mylist:index', ))


def add_movie_to_list(request, movie_id):
    if request.method == 'POST':
        form = AddMovieForm(request.POST)
        if form.is_valid():
            m = tmdb.Movies(id=movie_id)
            movie_info = m.info()
            user_movie_list = get_object_or_404(MovieList, list_name=form.cleaned_data['movie_lists'])
            obj, movie = Movie.objects.get_or_create(
                tmdb_id=movie_id,
                title=movie_info['title'],
                release_date=movie_info['release_date'],
                overview=movie_info['overview'],
                runtime=movie_info['runtime'],
                backdrop_url=movie_info['backdrop_path'],
                poster_url=movie_info['poster_path']
            )
            movie_membership = MovieListMembership(movie=obj, movie_list=user_movie_list,
                                                   date_added=timezone.now(), owner=request.user.userprofile)
            movie_membership.save()
            return HttpResponseRedirect(reverse('search:movie-detail', args=(movie_id,)))
    else:
        return render(request, 'search/index.html')


def set_movie_watched(request, list_id, movie_id):
    MovieListMembership.objects.filter(movie=movie_id).update(watched=True, date_watched=timezone.now())
    return HttpResponseRedirect(reverse('mylist:list-detail', args=(list_id,)))


def clear_movie_watched(request, list_id, movie_id):
    MovieListMembership.objects.filter(movie=movie_id).update(watched=False, date_watched=None)
    return HttpResponseRedirect(reverse('mylist:list-detail', args=(list_id,)))

mylist/templates/mylist/index.html
{% extends 'base_2column.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
{% block per_page_style %}
<link href="{% static 'mylist/mylist.css' %}" rel="stylesheet">
{% endblock per_page_style %}
<!-- SIDEBAR -->
{% block sidebar %}
	{% include sidebar %}
{% endblock %}

{% block main_content %}

{% block main_content_title %}
	<h1 class="title">My Lists</h1>
{% endblock main_content_title %}

{% block main_content_header %}
	<div  class="columns is-mobile">
		<div class="column">
			<div class="level toolbar material-shadow-d1">
				<div class="level-left is-expanded">
					<div class="level-item">
						<p class="subtitle is-5">
							<strong>{{ movie_count }}</strong> Movies
						</p>
					</div>
					<div class="level-item">
						<div class="field has-addons">
							<p class="control">
								<input class="input" type="text" placeholder="Find a movie in my lists">
							</p>
							<p class="control">
								<button class="button is-primary">
								Search
								</button>
							</p>
						</div>
					</div>
				</div>
				<div class="level-right">
					<div class="level-item">
						<a href="{% url 'mylist:new_list' %}" class="button is-primary">
							<span class="icon">
								<i class="fa fa-plus"></i>
							</span>
							<span>Add a new list</span>
						</a>
					</div>
					<div class="level-item"><a class="button">Manage Shared </a></div>
					<div class="level-item"><a id="renameBtn" class="button">Rename</a></div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
<!-- TOOLBAR -->
<!-- MAIN CONTENT -->

	{% include 'mylist/rename-modal.html' %}
	<div class="tile is-parent">
		<div class="tile is-child">
			<table class="table material-shadow-d1  movie-lists-table">
				<thead>
					<tr>
						<th>#</th>
						<th>List Name</th>
						<th>Shared</th>
						<th>Edit</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for list in my_lists %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td><a href="{% url 'mylist:list-detail' list.id %}">{{ list.list_name }}</a></td>
							<td>{{ list.shared }}</td>
							<td>
								<div class="field has-addons">
									<p class="control">
										<a href="{% url 'mylist:list-edit' list.id %}" class="button is-primary"> Edit </a>
									</p>
								</div>
							</td>
							<td>
								<div class="field">
									<p class="control">
										<label class="checkbox">
											<input type="checkbox" value="{{ list.id }}">
										</label>
									</p>
								</div>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

mylist/templates/mylist/movie-confirm-delete.html
{% extends 'base_2column.html' %}

{% block page_title %} Please Confirm {% endblock %}
{% load static %}
<!-- Bootstrap core CSS -->
{% block page_header %}
Please Confirm
{% endblock %}

{% block main_content %}

<div class="alert alert-warning" role="alert">
    Warning! You're about to delete <strong>{{ item.title }}</strong> from your list. Are
    you sure
    you want to do that?
</div>
<form action="" method="post">
    {% csrf_token %}
    <a href="{% url 'mylist:index' %}" role="button">Cancel</a>
    <button type="submit" class="btn btn-danger">Submit</button>
</form>
{% endblock %}

mylist/templates/mylist/movie-detail.html
{% extends 'search/base.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% block per_page_style %}
	<style type="text/css" media="screen">
		
	.box {
	min-height: 350px;
	border-radius: 0px;
	display: flex;
	align-items: center;
	justify-content: left;
	position: relative;
	}
	.box:before {
	content: ' ';
	display: block;
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	z-index: 1;
	opacity: 0.6;
	background-image: url("{{ backdrop }}{{ movie.backdrop_path }}");
	background-repeat: no-repeat;
	background-position: 50% 0;
	-ms-background-size: cover;
	-o-background-size: cover;
	-moz-background-size: cover;
	-webkit-background-size: cover;
	background-size: cover;
	}
	.box.movie-detail .title {
		color: #fff;
	}
	.box.movie-detail .subtitle {
		color: #f5f5f6;
	}
	.grad {
	min-height: 350px;
	border-radius: 0px;
	align-items: center;
	justify-content: left;
	position: relative;
	}
	.grad:before {
	content: ' ';
	display: block;
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	z-index: 2;
	background: black; /* For browsers that do not support gradients */
	background: -webkit-linear-gradient(left top, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Safari 5.1 to 6.0 */
	background: -o-linear-gradient(bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Opera 11.1 to 12.0 */
	background: -moz-linear-gradient(bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* For Firefox 3.6 to 15 */
	background: linear-gradient(to bottom right, rgba(0,0,0,0.8), rgba(0,0,0,0.5)); /* Standard syntax */
	}
	.media {
	padding:50px;
	z-index: 3;
	}
	.media-content .main-cast {
		margin-top: -1rem;
		margin-bottom: 0.5rem;
	}
	.media-content .block.title {
		margin-bottom: 0rem
	}
	.media-content .block.overview p {
		color: #fff;
	}
	.media-content .block.rating {
		color: #fff;
	}
	</style>
{% endblock %}
{% load static %}
<!-- Bootstrap core CSS -->
{% block main_content %}
	<div class="hero">
		<div class="grad">
			<div class="box movie-detail">
				
				<article class="media">
					<div class="media-left">
						<figure class="image">
							<img src="{{ poster }}{{ movie.poster_path }}" alt="Image">
						</figure>
					</div>
					<div class="media-content">
						<div class="block title">
							<h3 class="title is-3"> {{ movie.title }} </h3>
							<h5 class="subtitle is-5"> {{ movie.release_date }} </h5>
						</div>
						<p class="block rating"> Movie Rating </p>
						<div class="block is-48x48 main-cast">
							<img src="http://bulma.io/images/placeholders/48x48.png">
							<img src="http://bulma.io/images/placeholders/48x48.png">
						</div>
						<div class="block overview">
							<p>{{ movie.overview }}</p>
						</div>
						<div class="level is-fullwidth">
							<form action="{% url 'mylist:add_to_list' movie.id %}" method="post" accept-charset="utf-8">
								{% csrf_token %}
								<div class="field is-grouped">
									<p class="control">
										<span class="select">{{ add_movie_form.movie_lists }}</span>
									</p>
									<p class="control">
										<button class="button is-primary" type="submit" >Add</button>
									</p>
								</div>
							</form>
						</div>
					</div>
				</article>
			</div>
		</div>
	</div>
{% endblock %}

mylist/templates/mylist/movie-update-form.html
{% extends 'base_2column.html' %}

{% block page_title %} My Search {% endblock %}
{% load static %}
<!-- Bootstrap core CSS -->
{% block page_header %} My Search Results {% endblock %}
{% block main_content %}
<div class="jumbotron detail">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a type="button" href="{% url 'mylist:index' %}"
           class="btn btn-default">
            Cancel</a>
        <button type="submit" class="btn btn-defaut">Save</button>
    </form>
</div>
{% endblock %}

mylist/templates/mylist/movielist-detail.html
{% extends 'base_2column.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
<!-- SIDEBAR -->
{% block sidebar %}
  {% include sidebar %}
{% endblock %}
{% block main_content %}
  {% block main_content_title %}
    <h1 class="title">{{ list.list_name }}</h1>
  {% endblock main_content_title %}
  {% block main_content_header %}
    
    <div class="level">
      <div class="level-item">
        <div class="box has-text-centered movie-stats material-shadow-d1">
          <p class="title is-5">{{ list.list_name }}</p>
          <p class="subitle is-6"><strong>{{ movies_watched }}</strong> Movies Watched</p>
        <progress class="progress is-primary" value="{{ watched_percent }}" max="100"></progress>
      </div>
    </div>
    <div class="level-item">
      <div class="box has-text-centered movie-stats material-shadow-d1">
        <p class="title is-5">All My Movies</p>
        <p class="subitle is-6"><strong>{{ all_movies_watched }}</strong> Movies Watched</p>
      <progress class="progress is-primary" value="{{ all_movies_watched_percent }}" max="100"></progress>
    </div>
  </div>
  <div class="level-item">
    <div class="box has-text-centered movie-stats material-shadow-d1">
      <p class="title is-5">Shared Movies</p>
      <p class="subitle is-6"><strong>{{ movies_watched }}</strong> Movies Watched</p>
    <progress class="progress is-primary" value="{{ watched_percent }}" max="100"></progress>
  </div>
</div>
</div>
{% endblock main_content_header %}
{% block main_content_toolbar %}
  <div  class="columns is-mobile">
    <div class="column">
      <div class="level toolbar material-shadow-d1">
        <div class="level-left is-expanded">
          <div class="level-item">
            <p class="subtitle is-5">
              <strong>{{ movie_count }}</strong> Movies
            </p>
          </div>
          <div class="level-item">
            <div class="field has-addons">
              <p class="control">
                <input class="input" type="text" placeholder="Find a movie in my lists">
              </p>
              <p class="control">
                <button class="button is-primary" disabled="">
                Search
                </button>
              </p>
            </div>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item"><a id="editBtn" class="button" disabled>Edit</a></div>
        </div>
      </div>
    </div>
  </div>
{% endblock main_content_toolbar %}
<!-- MAIN CONTENT -->
<div class="tile is-parent">
<div class="tile is-child">
<table class="table material-shadow-d1">
  <caption></caption>
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Overview</th>
      <th>Date Added</th>
      <th>Date Watched</th>
      <th>Watched</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movie_list %}
      <tr>
        {% with forloop.counter as count %}
        <td>{{ count }}</td>
        <td><a href="{% url 'mylist:movie-detail' movie.movie_id %}">{{ movie.get_movie_title }}</a></td>
        <td>{{ movie.get_movie_overview }}</td>
        <td>{{ movie.date_added | date}}</td>
        {% if movie.watched is False %}
          <td> - </td>
          <td><a href="{% url 'mylist:set_watched' movie.movie_list_id movie.movie_id %}" class="button is-success is-outlined">Watched</td>
        {% else %}
          <td> {{ movie.date_watched | date }} </td>
          <td><a href="{% url 'mylist:clear_watched' movie.movie_list_id movie.movie_id %}" class="button is-success">Watched</td>
        {% endif %}
      {% endwith %}
    </tr>
  {% endfor %}
</tbody>
</table>
{% endblock %}

mylist/templates/mylist/movielist_form.html
{% extends 'base_2column.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
<!-- SIDEBAR -->
{% block sidebar %}
	{% include sidebar %}
{% endblock %}
{% block main_content %}
{% block main_content_title %}
   <h1 class="title">{{ list_name }}</h1>
{% endblock main_content_title %}


{% block main_content_header %}
{% endblock main_content_header %}


{% block main_content_toolbar %}
	<form action="" method="post">{% csrf_token %}
		<div class="field">
			{{form.list_name.label_tag}}
			<p class="control">
				{{ form.list_name }}
			</p>
		</div>
		<div class="field">
			<p class="control">
				<label class="checkbox">
					{{ form.shared }}
					Shared List
				</label>
			</p>
		</div>
		<div class="field">
			{{ form.shared_with.label_tag }}
			<p class="control">
				{{ form.shared_with }}
			</p>
		</div>
		<div class="field is-grouped">
			<p class="control">
				<button class="button is-primary">Submit</button>
			</p>
			<p class="control">
				<button class="button is-link">Cancel</button>
			</p>
		</div>
	</form>
{% endblock main_content_toolbar %}


{% endblock main_content %}

mylist/templates/mylist/rename-modal.html
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Rename List</p>
      <button class="delete"></button>
    </header>
    <section class="modal-card-body">
      <form action="{% url 'mylist:rename_list' list.id %}" id="rename-form" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="field">
          <p class="control">
          {{ rename_form.list_name }}
          </p>
        </div>
      </form>
    </section>
    <footer class="modal-card-foot">
      <a id="submit" class="button is-success">Save changes</a>
      <a class="button">Cancel</a>
    </footer>
  </div>
</div>

mylist/templates/mylist/sidebar_nav.html
<aside class="menu">
    <p class="menu-label"> My Lists </p>
    <ul class="menu-list">
        <li>
            <a href="{% url 'mylist:index' %}">All My Lists</a>
        </li>
        {% for list in my_lists %}
            <li>
                <a href="{% url 'mylist:list-detail' list.id %}">
                    {{ list.list_name }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <p class="menu-label"> Shared With Me </p>
    <ul class="menu-list">
    {% for list in lists_shared_with_me %}
            <li>
                <a href="{% url 'mylist:list-detail' list.id %}">
                    {{ list.list_name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</aside>