users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-ai'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-pi'),
    url(r'^settings/fl=(?P<pk>[0-9]+)$', views.user_settings_fl, name='user-settings-fl'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&search=$', views.search_users, name='search-users'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&add=(?P<add_pk>[0-9]+)$', views.add_friend, name='add-friend'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&remove=(?P<remove_pk>[0-9]+)$', views.remove_friend, name='remove-friend'),
]

users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    first_name = models.CharField(max_length=120, default='')
    last_name = models.CharField(max_length=120, default='')
    email = models.EmailField(max_length=256)
    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return "{0}'s Profile".format(self.user)

    def get_absolute_url(self):
        return reverse('user-settings-pi', kwargs={'pk': self.pk})


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

users/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm,  UserCreationForm
from django import forms
from .models import UserProfile


class UserLoginForm(AuthenticationForm): 
    username = forms.CharField(widget=forms.TextInput(
        attrs={'type': 'text', 'class': 'input',  'placeholder':  'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'type': 'password',  'class':  'input', 
               'placeholder':  'Password'}))

    class Meta(AuthenticationForm): 
        model = User
        fields = ['username',  'password']


class UserRegistrationForm(UserCreationForm): 
    username = forms.CharField(widget=forms.TextInput(
        attrs={'type': 'text', 'class': 'input',  'placeholder': 'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'type': 'password', 'class': 'input', 
               'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'type': 'password', 'class': 'input', 
               'placeholder': 'Re-Enter Password'}))

    class Meta: 
        model = User
        fields = ['username',  'password1',  'password2']

    def save(self,  commit=True): 
        user = super(UserRegistrationForm,  self).save(commit=False)

        if commit: 
            user.save()
        return user


class UserAccountInfoForm(ModelForm):
    class Meta:
        model = User
        fields = ['username']


class UserPersonalInfoForm(ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'type': 'text', 'class': 'input', 'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'type': 'text', 'class': 'input', 'placeholder': 'Last Name'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'type': 'email', 'class': 'input', 'placeholder': 'email@domaim.com'}))
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'email']



class SearchUsersForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'type': 'text','class':'input',
                                                           'placeholder': 'Add a friend...'}),
                            max_length=120)

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import UpdateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import UserLoginForm, UserRegistrationForm, UserPersonalInfoForm, SearchUsersForm
from django.shortcuts import render, redirect

'''
Login Class

Class Based View to log a user in
'''
class Login(LoginView):
    title = 'Login'
    template_name = 'users/form.html'
    authentication_form = UserLoginForm
    extra_context = {'title': title}

'''
Logout Class

Class Based View to log a user out
'''
class Logout(LogoutView):
    title = 'Login'
    template_name = 'users/form.html'
    next_page = 'login'
    extra_context = {'title': title}


class UserSettings(UpdateView):
    model = UserProfile
    template_name = 'users/user_settings_form.html'
    form_class = UserPersonalInfoForm


def user_settings_fl(request,pk):
    qs = UserProfile.objects.get(pk=pk).friends.all()
    add_friend_form = SearchUsersForm()
    context = {'friends_list': qs, 'add_friend_form': add_friend_form}
    return render(request, 'users/user_friends_form.html', context)


def search_users(request,pk):
    fl = UserProfile.objects.get(pk=pk).friends.all()
    
    if request.method =='GET':
        add_friend_form = SearchUsersForm(request.GET or None)
        if add_friend_form.is_valid():
            query = add_friend_form.cleaned_data['search']
            qs = User.objects.filter(username__istartswith=query)
            context = {'users_found': qs, 'add_friend_form': add_friend_form, 'friends_list': fl}
        return render(request, 'users/user_friends_form.html', context)
    else:
        add_friend_form = SearchUsersForm()
        context = {'users_found': 'None', 'add_friend_form': add_friend_form, 'friends_list': fl}
    return render(request, 'users/user_friends_form.html', context) 


def add_friend(request,pk,add_pk):
    owner = UserProfile.objects.get(pk=pk)
    friend = UserProfile.objects.get(pk=add_pk)
    owner.friends.add(friend)
    qs = UserProfile.objects.get(pk=pk).friends.all()
    add_friend_form = SearchUsersForm()
    context = {'friends_list': qs, 'add_friend_form': add_friend_form}

    return render(request, 'users/user_friends_form.html', context)

def remove_friend(request,pk,remove_pk):
    owner = UserProfile.objects.get(pk=pk)
    friend = UserProfile.objects.get(pk=remove_pk)
    owner.friends.remove(friend)
    qs = UserProfile.objects.get(pk=pk).friends.all()
    add_friend_form = SearchUsersForm()
    context = {'friends_list': qs, 'add_friend_form': add_friend_form}

    return render(request, 'users/user_friends_form.html', context)

def register_view(request):
    # Returns a new 'register view', allowing new users to register a new account

    title = 'Register'
    # Instantiate a new form if we receive a POST request.
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
        return redirect('/')
    else:
        form = UserRegistrationForm()
        context = {'form': form, 'title': title}
    return render(request, 'users/form.html', context)

users/templates/users/form.html
{% extends 'base.html' %}
{% load static %}
{% block per_page_style %}
   <link href="{% static 'users/login.css' %}" rel="stylesheet">
{% endblock per_page_style %}
{% block browse_hero %}
{% endblock browse_hero %}
{% block main_content %}
    <div class="section has-text-centered">
        <div class="box login">
           
           <h2 class="subtitle">{{ title }} </h2>
            <form action="" method="post"> {% csrf_token %}
                
                <div class="field">
                    <p class="control has-icons-left has-icons-right">
                        {{ form.username }}
                        <span class="icon is-small is-left">
                            <i class="fa fa-user-o"></i>
                        </span>
                    </p>
                </div>
                {% if title == 'Login' %}
                <div class="field">
                    <p class="control has-icons-left has-icons-right">
                        {{ form.password }}
                        <span class="icon is-small is-left">
                            <i class="fa fa-unlock-alt"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fa fa-warning"></i>
                        </span>  
                    </p>
                    {% if form.errors %}
                        <p class="help is-danger">This password is invalid</p>
                    {% endif %}
                </div>
                {% else %}
                <div class="field">
                    <p class="control has-icons-left has-icons-right">
                        {{ form.password1 }}
                        <span class="icon is-small is-left">
                            <i class="fa fa-unlock-alt"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fa fa-warning"></i>
                        </span>  
                    </p>
                    {% if form.errors %}
                        <p class="help is-danger">This password is invalid</p>
                    {% endif %}
                </div>
                <div class="field">
                    <p class="control has-icons-left has-icons-right">
                        {{ form.password2 }}
                        <span class="icon is-small is-left">
                            <i class="fa fa-unlock-alt"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fa fa-warning"></i>
                        </span>  
                    </p>
                    {% if form.errors %}
                        <p class="help is-danger">This password is invalid</p>
                    {% endif %}
                </div>

                {% endif %}
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button is-primary">Submit</button>
                    </p>
                    <p class="control">
                        <a href="{% url 'browse' %}" class="button is-link">Cancel</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
{% endblock main_content %}

users/templates/users/sidebar_nav.html
<aside class="menu">
    <p class="menu-label"> Settings </p>
    <ul class="menu-list">
        <li>
            <a href="{% url 'users:user-settings-ai' user.id %}">
                Account Info
            </a>
        </li>
        <li>
            <a href="{% url 'users:user-settings-pi' user.id %}">
                Personal Info 
            </a>
        </li>
        <li>
            <a href="{% url 'users:user-settings-fl' user.id %}">
                Friends List
            </a>
        </li>
    </ul>
</aside>

users/templates/users/user_friends_form.html
{% extends 'base_2column.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
{% block per_page_style %}
	<link href="{% static 'users/userprofile.css' %}" rel="stylesheet">
{% endblock per_page_style %}
<!-- SIDEBAR -->
{% block sidebar %}
	{% include 'users/sidebar_nav.html'%}
{% endblock %}
{% block main_content %}
	
	{% block main_content_header %}
	{% endblock main_content_header %}
	
	{% block main_content_toolbar %}
		
	{% endblock main_content_toolbar %}
	<!-- MAIN CONTENT -->
	<div class="tile is-ancestor">
		<div class="tile is-parent">
			<div class="tile is-child">
				<div class="box material-shadow-d1">
					<h4 class="title is-3">Find Users</h4>
					<div class="tile is-ancestor">
						<div class="tile is-parent">
							<form action="{% url 'users:search-users' user.id %}" method="get" accept-charset="utf-8" role="search">
								<div class="field has-addons">
									<p class="control is-expanded">
										{{ add_friend_form.search }}
									</p>
									<p class="control">
										<a class="button is-primary">
											Search
										</a>
									</p>
								</div>
							</form>
						</div>
					</div>
					<div class="tile is-ancestor wrap-tiles">
						{% for u in users_found %}
							<div class="tile is-3 is-parent">
								<div class="tile is-child box material-shadow-d1">
									<div class="level">
										<div class="level-left">
											<div class="level-item">
												{{u}}
											</div>
										</div>
										<div class="level-right">
											<div class="level-item">
												<div class="field">
													<div class="control">
														{% if u.userprofile in friends_list %}
															<a href="{% url 'users:remove-friend' user.id u.id %}" class="button is-danger is-small">Remove</a>
														{% else %}
															<a href="{% url 'users:add-friend' user.id u.id %}" class="button is-success is-small">Add</a>
														{% endif %}
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
					<h4 class="title is-3">My Friends</h4>
					<div class="tile is-ancestor wrap-tiles">
						{% for f in friends_list %}
							<div class="tile is-3 is-parent">
								<div class="tile is-child material-shadow-d1 box">
									<div class="level">
										<div class="level-left">
											<div class="level-item">
												{{f.user}}
											</div>
										</div>
										<div class="level-right">
											<div class="level-item">
												<div class="field">
													<div class="control">
														<a href="{% url 'users:remove-friend' user.id f.id %}" class="button is-danger is-small">Remove</a>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							{% if forloop.counter|divisibleby:4 %}
							</div>
							<div class="tile is-ancestor">
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

users/templates/users/user_settings_form.html
{% extends 'base_2column.html' %}
{% block page_title %} Our List | {{ user }} {% endblock %}
{% load static %}
{% block per_page_style %}
	<link href="{% static 'users/userprofile.css' %}" rel="stylesheet">
{% endblock per_page_style %}
<!-- SIDEBAR -->
{% block sidebar %}
	{% include 'users/sidebar_nav.html'%}
{% endblock %}
{% block main_content %}
	
	{% block main_content_header %}
		<div class="tile is-ancestor">
			<div class="tile is-parent">
				<div class="tile is-child">
					<div class="box material-shadow-d1">
						<h1 class="title is-size-4-mobile has-text-centered"> Profile Settings </h1>
					</div>
				</div>
			</div>
		</div>
	{% endblock main_content_header %}
	
	{% block main_content_toolbar %}
		
	{% endblock main_content_toolbar %}
	<!-- MAIN CONTENT -->
	<div class="tile is-ancestor is-flex-mobile">
		<div class="tile is-parent">
			<div class="tile is-child">
				<div class="box material-shadow-d1">
					<h3 class="title is-4 is-size-4-mobile">Personal Info</h2>

						<form action="" method="post">
							{% csrf_token %}
							<label class="label">Name</label>
							<div class="field is-grouped is-hidden-mobile"">
								<p class="control has-icons-left">
									{{ form.first_name }}
									<span class="icon is-small is-left">
										<i class="fa fa-user"></i>
									</span>
								</p>
								<p class="control has-icons-left">
									{{ form.last_name }}
									<span class="icon is-small is-left">
										<i class="fa fa-user"></i>
									</span>
								</p>
							</div>
							<div class="field is-hidden-desktop">
								<p class="control has-icons-left">
									{{ form.first_name }}
									<span class="icon is-small is-left">
										<i class="fa fa-user"></i>
									</span>
								</p>
							</div>
							<div class="field is-hidden-desktop">
								<p class="control has-icons-left">
									{{ form.last_name }}
									<span class="icon is-small is-left">
										<i class="fa fa-user"></i>
									</span>
								</p>
							</div>
							<label class="label">Email</label>
							<div class="field">
								<p class="control has-icons-left">
									{{ form.email }}
									<span class="icon is-small is-left">
										<i class="fa fa-envelope"></i>
									</span>
								</p>
							</div>
							<div class="field is-grouped">
								<p class="control">
									<a class="button is-primary" onclick="$(this).closest('form').submit()" >
										Submit
									</a>
								</p>
								<p class="control">
									<a class="button is-light">
										Cancel
									</a>
								</p>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}