mylist/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mylist'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new_list$', views.add_new_list, name='new_list'),
    url(r'^rename=(?:(?P<list_id>[0-9]+))?$', views.rename_list, name='rename_list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.MovieListEditView.as_view(), name='list-edit'),
    url(r'^add=(?P<movie_id>[0-9]+)', views.add_movie_to_list, name='add_to_list'),
    url(r'^(?P<pk>[0-9]+)/list/$', views.MovieListView.as_view(), name='list-detail'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.MovieDetailView.as_view(), name='movie-detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.MovieUpdateView.as_view(), name='movie-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.MovieDeleteView.as_view(), name='movie-delete'),
    url(r'^list=(?P<list_id>[0-9]+)&set_watched=(?P<movie_id>[0-9]+)', views.set_movie_watched, name='set_watched'),
    url(r'^list=(?P<list_id>[0-9]+)&clear_watched=(?P<movie_id>[0-9]+)', views.clear_movie_watched, name='clear_watched'),


]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    url(r'^$', views.TopThisMonth.as_view(), name='index'),
    url(r'^browse=', views.SearchView.as_view(), name='browse'),
    url(r'^movies$', views.BrowseMovies.as_view(), name='movies'),
    url(r'^genre=(?P<genre_id>[0-9]+)$', views.GenreView.as_view(), name='by_genre'),
    url(r'^year=(?P<year>[0-9]+)$', views.YearView.as_view(), name='by_year'),
    url(r'^top-this-month', views.TopThisMonth.as_view(), name='top-this-month'),
    url(r'^top-this-year', views.TopThisYear.as_view(), name='top-this-year'),
    url(r'^(?P<movie_id>[0-9]+)$', views.MovieDetail.as_view(), name='movie-detail'),
]

users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-ai'),
    url(r'^settings/(?P<pk>[0-9]+)/$', views.UserSettings.as_view(), name='user-settings-pi'),
    url(r'^settings/fl=(?P<pk>[0-9]+)$', views.user_settings_fl, name='user-settings-fl'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&search=$', views.search_users, name='search-users'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&add=(?P<add_pk>[0-9]+)$', views.add_friend, name='add-friend'),
    url(r'^settings/fl=(?P<pk>[0-9]+)&remove=(?P<remove_pk>[0-9]+)$', views.remove_friend, name='remove-friend'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">
        <title>{% block page_title %}{% endblock %}</title>
        <!-- {% load static %} -->
        <!-- Bootstrap core CSS -->
        <link href="{% static '/css/bulma.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <!--<link href="{% static 'mylist/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">-->
        <!-- Custom styles for this template -->
        <link href="{% static '/css/base-main.css' %}" rel="stylesheet">
        {% block per_page_style %}
        {% endblock %}
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            {% include 'navbar.html' %}
        </header>
        
        <section class="hero">
            {% block browse_hero %}
                {% include 'search/browse-hero.html' %}
            {% endblock browse_hero %}
        </section>
        
        <section class="section">
            <div class="container">
                {% block main_content_header %}
                {% endblock %}
                {% block main_content %}
                {% endblock %}
            </div>
        </section>
        <footer class="footer">
            {% include 'footer.html' %}
        </footer>
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="{% static '/js/jq-modal.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/dropdown.js' %}"></script>
        {% block per_page_jquery %}
        {% endblock per_page_jquery %}
        <!--<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>-->
    </body>
</html>

templates/base_2column.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">
        <title>{% block page_title %}{% endblock %}</title>
        <!-- {% load static %} -->
        <!-- Bootstrap core CSS -->
        <link href="{% static '/css/bulma.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <!--<link href="{% static 'mylist/css/ie10-viewport-bug-workaround.css' %}"
            rel="stylesheet">-->
            <!-- Custom styles for this template -->
            <link href="{% static '/css/dropdown.css' %}" rel="stylesheet">
            <link href="{% static '/css/base-main.css' %}" rel="stylesheet">
            {% block per_page_style %}
            {% endblock %}

            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
            <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
        </head>
        <body>
            
            <header>
            {% include 'navbar.html' %}
            </header>

            <section class="section">
                    <div class="columns">
                        <div class="column is-2 sidebar">
                            {% block sidebar %}    
                            {% endblock %}
                        </div>
                        <div class="column main-col">
                            {% block main_content %}

                            <section class="section">
                            {% block main_content_header %}
                            {% endblock main_content_header %}
                            </section>

                            <section class="section">
                            {% block main_content_toolbar %}
                            {% endblock main_content_toolbar %}
                            </section>

                            {% endblock main_content %} 
                        </div>
                    </div>
            </section>
            
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script type="text/javascript" src="{% static '/js/jq-modal.js' %}"></script>
            <script type="text/javascript" src="{% static '/js/dropdown.js' %}"></script>
            <!--<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>-->
        </body>
    </html>

templates/footer.html
<div class="container">
  <div class="content has-text-centered">
    <p>
      <strong>Ourlist</strong> by <a href="http://mintroini.com">Mike Introini</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC ANS 4.0</a>.
    </p>
    <p>
      <a class="icon" href="https://github.com/introini/ourlist">
        <i class="fa fa-github"></i>
      </a>
    </p>
  </div>
</div>

templates/navbar.html
<nav class="navbar">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'browse' %}"><h1 class="title">Kyū</h1></a>
    <a class="navbar-item is-hidden-mobile" href="{% url 'search:movies' %}">Movies</a>
    <a class="navbar-item is-hidden-mobile" href="#">TV Shows</a>
    <div class="navbar-burger" data-target="navMenu">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <div class="navbar-menu" id="navMenu">
    <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable is-hidden-desktop">
        <a class="navbar-link">Browse</a>
        <div class="navbar-dropdown" href="{% url 'search:movies' %}">
          <a class="navbar-item">
            Movies
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="{% url 'search:movies' %}" disabled>
            TV Shows
          </a>
        </div>
      </div>
    </div>
    <div class="navbar-end">
      {% if user.is_authenticated %}
      <a class="navbar-item" href="{% url 'mylist:index' %}">My Lists</a>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">{{ user }}</a>
          <div class="navbar-dropdown">
            <a class="navbar-item" href="{% url 'users:user-settings-ai' user.id %}">
              Settings
            </a>
            <hr class="navbar-divider">
            <a href="{% url 'users:logout' %}" class="navbar-item">
              Logout
            </a>
          </div>
        {% else %}
          <a class="navbar-item" href="{% url 'users:login' %}">Login</a>
          <a class="navbar-item" href="{% url 'users:register' %}">Register</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>